import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';
import { Container, createTheme, MantineProvider } from "@mantine/core";
import '@mantine/notifications/styles.css';
import { Notifications } from "@mantine/notifications";
import { ModalsProvider } from '@mantine/modals';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const theme = createTheme({
  scale: 0.5
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MantineProvider theme={theme}>
          <Notifications />
          <ModalsProvider>
            <Container px={0} size={'lg'}>
              {children}
            </Container>
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}

